# Generated by Django 4.0.3 on 2022-04-09 21:32

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(blank=True, max_length=150, null=True)),
                ('typeClient', models.CharField(blank=True, choices=[('PERSONNE', 'Personne'), ('ENTREPRISE', 'Entreprise')], default='PERSONNE', max_length=12)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('pays', django_countries.fields.CountryField(max_length=2)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
