# Generated by Django 4.0.3 on 2022-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='statut',
            field=models.CharField(blank=True, choices=[('ENSTOCK', 'Enstock'), ('RUPTURE', 'Rupture')], default='ENSTOCK', max_length=10),
        ),
    ]
