# Generated by Django 4.0.3 on 2022-04-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_matierepremiere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatierePremiere',
        ),
    ]
