# Generated by Django 4.0.3 on 2022-04-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_stocks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
